name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Download CEF (Linux)
      if: runner.os == 'Linux'
      run: curl -o cef.tar.bz2 https://cef-builds.spotifycdn.com/cef_binary_93.1.11%2Bg9e254fa%2Bchromium-93.0.4577.63_linux64_minimal.tar.bz2

    - name: Download CEF (macOS)
      if: runner.os == 'macOS'
      run: curl -o cef.tar.bz2 https://cef-builds.spotifycdn.com/cef_binary_93.1.11%2Bg9e254fa%2Bchromium-93.0.4577.63_macosx64_minimal.tar.bz2

    - name: Extract CEF (non-Windows)
      if: runner.os != 'Windows'
      run: |
        mkdir cef
        tar xf cef.tar.bz2 -C cef --strip-components 1
        echo "CEF_ROOT=${PWD}/cef" >> $GITHUB_ENV

    - name: Download CEF (Windows)
      if: runner.os == 'Windows'
      run: curl -o cef.tar.bz2 https://cef-builds.spotifycdn.com/cef_binary_93.1.11%2Bg9e254fa%2Bchromium-93.0.4577.63_windows64_minimal.tar.bz2

    - name: Extract CEF (Windows)
      if: runner.os == 'Windows'
      run: |
        7z x cef.tar.bz2
        7z x cef.tar
        echo "CEF_ROOT=${PWD}/cef_binary_93.1.11+g9e254fa+chromium-93.0.4577.63_windows64_minimal" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Install boost and SDL2 (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libboost-dev libsdl2-dev

    - name: Install boost and SDL2 (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install boost sdl2

    - name: Install boost (Windows)
      if: runner.os == 'Windows'
      run: |
        curl -L -o install_boost.exe https://downloads.sourceforge.net/project/boost/boost-binaries/1.77.0/boost_1_77_0-msvc-14.2-64.exe
        ./install_boost.exe
      
    - name: Install SDL2 (Windows)
      if: runner.os == 'Windows'
      run: |
        curl -o SDL2.zip https://www.libsdl.org/release/SDL2-devel-2.0.16-VC.zip
        unzip SDL2.zip
        ls
        echo "SDL2_ROOT=${PWD}/SDL2" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Show artifacts
      run: ls ${{github.workspace}}/build/src/Release/

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
